# Regenerates the platform-specific file-association configs from the single source of truth
# (`file_associations.py`). Mirrors the codegen convention of `generate_resource_doc.py`.
#
# Outputs:
#   - nfs-resources-converter-mime.xml        (Linux MIME database)
#   - nfs-resources-converter.desktop         (Linux desktop entry)
#   - windows-installer.filetypes.iss         (Windows installer [Registry] rows, #include-d)
#
# Run `python generate_build_configs.py` after editing `file_associations.py` to keep macOS,
# Windows and Linux packaging in sync. The macOS `.spec` imports the module directly and needs
# no generated file.

from file_associations import FILE_ASSOCIATIONS, mime_type, prog_id

GENERATED_NOTICE = 'AUTO-GENERATED by generate_build_configs.py from file_associations.py - do not edit by hand'


def write_if_changed(path: str, contents: str) -> None:
    try:
        old_contents = open(path, 'r', encoding='utf-8').read()
    except FileNotFoundError:
        old_contents = None
    if old_contents == contents:
        print('Skip writing ' + path + ': no changes')
    else:
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(contents)
        print('Wrote ' + path)


def generate_mime_xml() -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<!-- {GENERATED_NOTICE} -->',
        '<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">',
    ]
    for entry in FILE_ASSOCIATIONS:
        ext = entry['extension']
        lines.append(f'  <mime-type type="{mime_type(ext)}">')
        lines.append(f'    <comment>{entry["name"]}</comment>')
        lines.append(f'    <glob pattern="*.{ext}"/>')
        lines.append('  </mime-type>')
    lines.append('</mime-info>')
    return '\n'.join(lines) + '\n'


def generate_desktop() -> str:
    mime_types = ''.join(f'{mime_type(entry["extension"])};' for entry in FILE_ASSOCIATIONS)
    lines = [
        '[Desktop Entry]',
        f'# {GENERATED_NOTICE}',
        'Name=NFS Resources Converter',
        'Exec=nfs-resources-converter %f',
        'Icon=/usr/share/icons/hicolor/256x256/apps/nfs-resources-converter.ico',
        'Type=Application',
        'Categories=Development;',
        f'MimeType={mime_types}',
        'Terminal=false',
    ]
    return '\n'.join(lines) + '\n'


def generate_windows_filetypes() -> str:
    lines = [f'; {GENERATED_NOTICE}']
    for entry in FILE_ASSOCIATIONS:
        ext = entry['extension']
        name = entry['name']
        pid = prog_id(ext)
        lines.append('')
        lines.append(f'; .{ext}')
        lines.append(f'Root: HKCR; Subkey: ".{ext}"; ValueType: string; ValueName: ""; '
                     f'ValueData: "{pid}"; Flags: uninsdeletevalue')
        lines.append(f'Root: HKCR; Subkey: "{pid}"; ValueType: string; ValueName: ""; '
                     f'ValueData: "{name}"; Flags: uninsdeletekey')
        lines.append(f'Root: HKCR; Subkey: "{pid}\\DefaultIcon"; ValueType: string; ValueName: ""; '
                     f'ValueData: "{{app}}\\nfs-resources-converter-{{#AppVersion}}.exe,0"')
        lines.append(f'Root: HKCR; Subkey: "{pid}\\shell\\open\\command"; ValueType: string; ValueName: ""; '
                     f'ValueData: """{{app}}\\nfs-resources-converter-{{#AppVersion}}.exe"" ""%1"""')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    write_if_changed('nfs-resources-converter-mime.xml', generate_mime_xml())
    write_if_changed('nfs-resources-converter.desktop', generate_desktop())
    write_if_changed('windows-installer.filetypes.iss', generate_windows_filetypes())
