; AUTO-GENERATED by generate_build_configs.py from file_associations.py - do not edit by hand

; .ffn
Root: HKCR; Subkey: ".ffn"; ValueType: string; ValueName: ""; ValueData: "NFSResourcesConverter.ffn"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "NFSResourcesConverter.ffn"; ValueType: string; ValueName: ""; ValueData: "FFN Bitmap Font File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "NFSResourcesConverter.ffn\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\nfs-resources-converter-{#AppVersion}.exe,0"
Root: HKCR; Subkey: "NFSResourcesConverter.ffn\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\nfs-resources-converter-{#AppVersion}.exe"" ""%1"""

; .fsh
Root: HKCR; Subkey: ".fsh"; ValueType: string; ValueName: ""; ValueData: "NFSResourcesConverter.fsh"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "NFSResourcesConverter.fsh"; ValueType: string; ValueName: ""; ValueData: "FSH Image Archive File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "NFSResourcesConverter.fsh\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\nfs-resources-converter-{#AppVersion}.exe,0"
Root: HKCR; Subkey: "NFSResourcesConverter.fsh\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\nfs-resources-converter-{#AppVersion}.exe"" ""%1"""

; .qfs
Root: HKCR; Subkey: ".qfs"; ValueType: string; ValueName: ""; ValueData: "NFSResourcesConverter.qfs"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "NFSResourcesConverter.qfs"; ValueType: string; ValueName: ""; ValueData: "QFS Compressed Image Archive File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "NFSResourcesConverter.qfs\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\nfs-resources-converter-{#AppVersion}.exe,0"
Root: HKCR; Subkey: "NFSResourcesConverter.qfs\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\nfs-resources-converter-{#AppVersion}.exe"" ""%1"""
