name: Unit tests
on:
  pull_request:
    types: [synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: test
        run: python -m unittest
